"""word and sentence

Revision ID: d1195c122049
Revises: 724f184d1842
Create Date: 2025-09-13 01:50:13.749043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1195c122049'
down_revision: Union[str, Sequence[str], None] = '724f184d1842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentences',
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('additional', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('words',
    sa.Column('en', sa.String(), nullable=False),
    sa.Column('ru', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    op.drop_table('sentences')
    # ### end Alembic commands ###
